version: 0.2
env:
  variables:
    AWS_REGION: "ap-northeast-1"
    ECR_REPOS: "ECR_REPOS"
    
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
  build:
    commands:
      - ./gradrew build
      - echo $ECR_REPOS
      - BRANCH=$(git symbolic-ref --short HEAD)
      - echo $BRANCH
      - TAG=$ECR_REPOS:$BRANCH
      - echo $TAG
      - docker build -t $TAG . 
      - docker tag $TAG $TAG
  post_build:
    commands:
      - docker push $TAG

artifacts:
  files:
    - build/reports/**/*
  discard-paths: no