version: 0.2
env:
  variables:
    ECR_REPOS: "ECR_REPOS"
    
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - ./gradlew build
      - echo $ECR_REPOS
      - BRANCH=${git branch --contains=HEAD}
      - echo $BRANCH
      - TAG=$ECR_REPOS:$BRANCH
      - echo $TAG
      - docker build -t $TAG . 
      - docker images
  post_build:
    commands:
      - docker push $TAG

artifacts:
  files:
    - build/reports/**/*
  discard-paths: no
  
cache:
  paths:
    - '/root/.m2/**/*'