version: 0.2
env:
  variables:
    ECR_REPOS: "ECR_REPOS"
    
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - ./gradlew build
      - echo $ECR_REPOS
      - BRANCH=${CODEBUILD_WEBHOOK_TRIGGER#branch/}
      - VERSION=${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - TAG_BRANCH=$ECR_REPOS:$BRANCH
      - TAG_VERSION=$ECR_REPOS:$VERSION
      - docker build -t $TAG_BRANCH .
      - docker tag $TAG_BRANCH $TAG_VERSION
  post_build:
    commands:
      - docker push $TAG_BRANCH
      - docker push $TAG_VERSION
		- printf '{"Version":"1.0","ImageURI":"%s"}' $TAG_BRANCH > imageDetail.json
 
artifacts:
  files:
    - build/reports/**/*
	- imageDetail.json
	- appspec.yaml
	- buildspec.yml
	- taskdef.json
  discard-paths: no
 
cache:
  paths:
    - '/root/.m2/**/*'