version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "<TASK_DEFINITION>" 
        LoadBalancerInfo:
            ContainerName: "spring-boot-ecs-sample-container"
            ContainerPort: "8080"
#Hooks:
#    - AfterAllowTestTraffic: "arn:aws:lambda:ap-northeast-1:903921708000:function:SpringBootECSTestLambdaFunctionToValidateTraffic"